Sbra 357 image ci cd
AI4SIM/model-collection pull request #26
Opened 2022-04-25 16:03 UTC by rmslm

Create and push docker images for each use case

2022-05-03 09:05 UTC, rdruilhe reviewed
You should not have 3 identical dockerfile. It is more complicated to maintain. I suggest to have a single version of this file and to have the variation using the ARG in the dockerfile in a script

2022-05-03 09:37 UTC, rdruilhe approved these changes

2022-05-04 07:32 UTC, rdruilhe requested changes
To avoid downloading the whole git repository, Lionel suggest to create a multistage Dockerfile with a first step including an image dedicated to download the files. Then, in the final image, a copy of the correct subfolders is made between the downloader and image. I agree with this way of doing stuffs.

2022-05-16 12:10 UTC, rmslm commented
> To avoid downloading the whole git repository, Lionel suggest to create a multistage Dockerfile with a first step including an image dedicated to download the files. Then, in the final image, a copy of the correct subfolders is made between the downloader and image. I agree with this way of doing stuffs.

This is not related to this PR. please see branch SBRA-357-propose-dockerfile.

2022-05-16 12:36 UTC, A669015 approved these changes

2022-05-16 12:38 UTC, rdruilhe approved these changes

2022-05-16 12:42 UTC, merged